name: Windows Release ZIP

on:
  push:
    tags:
      - 'v*' # Triggers the workflow only when you push a version tag like v1.0.0


jobs:
  build-and-release-windows:
    runs-on: windows-2022
    permissions:
      contents: write # Required to upload assets to a GitHub Release

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v6

      # 1. Install Qt 6.8.X
      - name: Install Qt 6.8
        uses: jurplel/install-qt-action@v4
        with:
          # Specify your target Qt 6 version (e.g., '6.8.0', '6.5.2', or '6.8.*')
          version: '6.8.*'
          # Enable built-in action caching to speed up subsequent workflow runs
          cache: 'true'
          install-deps: 'true'
          # Add any optional modules your project requires
          modules: 'qtserialport'
          # Setup bare minimum instalation
          archives: 'qtbase qtserialport'

      # 2. Build with Visual Studio 2022
      - name: Build Application
        run: |
          mkdir build
          cd build
          # CMAKE_BUILD_TYPE for MSVC useless
          cmake -DCMAKE_INSTALL_PREFIX="../dist" ..
          cmake --build . --config Release --parallel --verbose
          cmake --install . --config Release

      # 3. Deploy Qt Dependencies (windeployqt)
      - name: Deploy Qt Dependencies
        shell: pwsh
        run: |
          # Find MSVC compiler path
          $vsPath = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
          $env:VCToolsRedistDir = Get-ChildItem -Path "$vsPath\VC\Redist\MSVC" | Sort-Object -Descending | Select-Object -First 1 -ExpandProperty FullName
          $env:VCINSTALLDIR = "$vsPath\VC\"

          windeployqt --release --no-compiler-runtime "dist/bin/spdrwc.exe"


      # 4. Rename dir dir
      - name: Rename dist dir
        shell: pwsh
        run: |
          $TAG_NAME = $env:GITHUB_REF -replace '^refs/tags/'
          mv "dist" "spdrwc-$TAG_NAME-win64"
          echo "FINAL_DISTDIR=spdrwc-$TAG_NAME-win64" >> $env:GITHUB_ENV
          echo "FINAL_ZIP=spdrwc-$TAG_NAME-win64.zip" >> $env:GITHUB_ENV

      # 5. Build ZIP archive
      - name: Create Target ZIP
        shell: pwsh
        run: |
          Compress-Archive -Path "$env:FINAL_DISTDIR" -DestinationPath "$env:FINAL_ZIP"

      - name: Create GitHub Release and Upload Artifact
        uses: softprops/action-gh-release@v3
        with:
          files: ${{ env.FINAL_ZIP }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
